set(USERSPACE_COMPILE_OPTIONS -static -Wl,-gc-sections)
set(USERSPACE_LINK_OPTIONS -static)

add_subdirectory("cat")
#add_subdirectory("dhcpcl")
add_subdirectory("getty")
add_subdirectory("init")
add_subdirectory("login")
add_subdirectory("ls")
add_subdirectory("mkdir")
#add_subdirectory("mount")
#add_subdirectory("monowm")
#add_subdirectory("ping")
#add_subdirectory("ps")
add_subdirectory("shell")
add_subdirectory("stat")
#add_subdirectory("su")
#add_subdirectory("touch")
#add_subdirectory("tee")

#add_subdirectory("gpttest")
add_subdirectory("vmmtest")
