set(CMAKE_SYSTEM_NAME monolith)
set(CMAKE_C_COMPILER clang)

set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
set(CMAKE_C_COMPILER_WORKS TRUE)

set(CMAKE_C_FLAGS ${CMAKE_C_FLAGS} "-target x86_64-none-elf")
set(CMAKE_ASM_FLAGS ${CMAKE_ASM_FLAGS} "-target x86_64-none-elf")
